version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: baltex-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: baltex-app
    ports:
      - "5432:5432" # Если порт 5432 занят, измените левую цифру на "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
