name: Deploy PWA Application

on:
  push:
    branches:
      - main # Скрипт срабатывает при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/actions/checkout@v4

      - name: Deploy to Reg.ru VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /root/baltex/baltex-app
            git pull origin main
            docker-compose -f docker-compose.prod.yml up -d --build
            docker image prune -f # Удаляет старые ненужные слои сборки, чтобы не забивать диск сервера
